{% set name = "mkl_random" %}
{% set version = "1.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/IntelPython/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e1bcdd3efbffef1416fcc556cd8215dd3a89887baf5e50b596573438a137ed3e
  patches:
    # Upstream 1.5.0 still has requires-python <3.15.
    - patches/0001-enable-python-3.15.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps . -vv
  ignore_run_exports:
    - blas
  skip: true  # [osx or (not x86_64) or py<310 or py>315]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base
  host:
    - python
    - pip
    - meson-python >=0.16.0
    - meson >=1.8.3
    - cython
    - mkl-devel {{ mkl }}
    - numpy-base {{ numpy }}
  run:
    - python
    - mkl
    - numpy >=1.26.4

test:
  imports:
    - mkl_random
    - mkl_random.mklrand
  commands:
    - pip check
    - pytest --pyargs mkl_random
  requires:
    - pip
    - pytest

about:
  home: https://github.com/IntelPython/mkl_random
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  description: NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
  summary: Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.
  dev_url: https://github.com/IntelPython/mkl_random
  doc_url: https://github.com/IntelPython/mkl_random

extra:
  skip-lints:
    - cbc_dep_in_run_missing_from_host
  recipe-maintainers:
    - oleksandr-pavlyk
