{% set version = "1.3.0" %}

package:
  name: mkl_random
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_random/archive/{{ version }}.tar.gz
  sha256: 4f4d6ee649e694eb94bc0a039f4db259d329a901bc706cb1648c41ebfa96d35e
  patches:
    - 0001-fix-pyproject-toml.patch

build:
  number: 0
  skip: true  # [not x86]
  # numpy-base 2.3.0 no longer supports Python 3.10: https://numpy.org/devdocs/release/2.3.0-notes.html
  skip: True  # [py<311 or osx]
  script: {{PYTHON}} -m pip install --no-build-isolation --no-deps . -vv
  script_env:
    - MKLROOT={{ PREFIX }}
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ stdlib('c') }}  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython 3
    - mkl-devel 2025.*
    - numpy-base >=2.3,<3
    - pip
    # numpy-base 2.3.3 requires setuptools <74
    # The patch changes license format to {text = "BSD"} which works with setuptools <74
    - setuptools >=64,<74
    - wheel
  run:
    - python
    - mkl
    - numpy >=1.16,<3

test:
  commands:
    - pip check
    - pytest --pyargs mkl_random
  requires:
    - pip
    - pytest
    - mkl-service
    - numpy
  imports:
    - mkl_random
    - mkl_random.mklrand

about:
  home: https://github.com/IntelPython/mkl_random
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  description: NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
  summary: Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.
  dev_url: https://github.com/IntelPython/mkl_random
  doc_url: https://github.com/IntelPython/mkl_random

extra:
  skip-lints:
    - cbc_dep_in_run_missing_from_host
  recipe-maintainers:
    - oleksandr-pavlyk
