{% set version = "1.2.2" %}

package:
  name: mkl_random
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_random/archive/v{{ version }}.post1.tar.gz
  sha256: 7f3fd565c55e9fc83bc617764ba631f716041e9c58d6805fcf864928ff2b4b33
  patches:
    - patches/0001-fix-sat-5359.patch

build:
  number: 2
  skip: true  # [not x86]
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [unix]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - mkl-devel  {{ mkl }}
    - cython
    - numpy-base {{ numpy }}
  run:
    - python
    - mkl
    - {{ pin_compatible('numpy') }}

test:
  # nose is incompatible with python 3.12
  commands:                                            # [py<312]
    - nosetests -v -e test_hypergeometric mkl_random   # [py<312]
  requires:                                            # [py<312]
    - nose                                             # [py<312]
  imports:
    - mkl_random
    - mkl_random.mklrand

about:
  home: https://github.com/IntelPython/mkl_random
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  description: NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
  summary: Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.
  dev_url: https://github.com/IntelPython/mkl_random
  doc_url: https://github.com/IntelPython/mkl_random

extra:
  recipe-maintainers:
    - oleksandr-pavlyk
