{% set version = "1.2.1" %}

package:
  name: mkl_random
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_random/archive/v{{ version }}.tar.gz
  sha256: 722d3e383a1501749a7ba1f759e7cd1e1ecd7b0298fe6f7591e17102cf67484c
  patches:
    - 0001-removing-gcc-pragma-windows.patch                # [win]
    - 0002-remove-warning-count-in-tests.patch

build:
  number: 2
  # numpy no longer supports python 3.6 and lower
  skip: true  # [(win and py27) or ppc64le or py<37]
  ignore_run_exports:
    - blas
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - mkl-devel  {{ mkl }}
    - cython
    - numpy-base {{ numpy }}
  run:
    - python
    - mkl
    - numpy >={{ numpy }},<2.0a0

test:
  commands:
    - nosetests -v mkl_random
  requires:
    - nose
  imports:
    - mkl_random
    - mkl_random.mklrand

about:
  home: http://github.com/IntelPython/mkl_random
  license: BSD 3-Clause
  license_file: LICENSE.txt
  description:
      NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library,
      mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
  summary:
      Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.


extra:
  recipe-maintainers:
    - oleksandr-pavlyk
