{% set name = "mkl_random" %}
{% set version = "1.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/IntelPython/{{ name }}/archive/{{ version }}.tar.gz
  sha256: bf9a1e946648cf632f1774734aad465636228b19e817fa2845f13d15b01d4865

build:
  number: 0
  script: {{PYTHON}} -m pip install --no-build-isolation --no-deps . -vv
  script_env:
    - MKLROOT={{ PREFIX }}
  ignore_run_exports:
    - blas
  skip: true  # [py<310 or py>314]
  skip: true  # [osx]
  skip: true  # [linux and aarch64]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython 3
    - mkl-devel {{ mkl }}
    - numpy-base {{ numpy }}
    - setuptools >=77
  run:
    - python
    - mkl
    - numpy >=1.26.4

test:
  imports:
    - mkl_random
    - mkl_random.mklrand
  commands:
    - pip check
    - pytest --pyargs mkl_random
  requires:
    - pip
    - pytest

about:
  home: https://github.com/IntelPython/mkl_random
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  description: NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
  summary: Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.
  dev_url: https://github.com/IntelPython/mkl_random
  doc_url: https://github.com/IntelPython/mkl_random

extra:
  skip-lints:
    - cbc_dep_in_run_missing_from_host
  recipe-maintainers:
    - oleksandr-pavlyk
