{% set version = "1.2.0" %}

package:
  name: mkl_random
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_random/archive/v{{ version }}.post0.tar.gz
  sha256: fa569a82797dbc6d5eb9a237c632692f85fef4857b01b98a75f12e15a1e8643e

build:
  number: 1
  skip: true  # [win and py27]
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - mkl-devel
    - cython
    - numpy 1.14.*    # [osx]
    - numpy    # [not osx]
  run:
    - python
    - mkl
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - nosetests -v mkl_random
  requires:
    - nose
    - mkl-service
    - numpy >=1.14
  imports:
    - mkl_random
    - mkl_random.mklrand

about:
  home: http://github.com/IntelPython/mkl_random
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
  summary: Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.


extra:
  recipe-maintainers:
    - oleksandr-pavlyk
