{% set version = "1.2.7" %}

package:
  name: mkl_random
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_random/archive/v{{ version }}.tar.gz
  sha256: b6d39f4847921b6603201a491225b086aa75a1c1667ea7068b8813e0514133f7

build:
  number: 0
  skip: true  # [not x86]
  skip: True  # [py<39]
  script: {{PYTHON}} -m pip install --no-build-isolation --no-deps .
  script_env:
    - MKLROOT={{PREFIX}}
  ignore_run_exports:
    - blas

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - mkl-devel  {{ mkl }}
    - cython 3
    - numpy >=1.16
  run:
    - python
    - mkl
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - pip check
    - pytest --pyargs mkl_random
  requires:
    - pip
    - pytest
    - mkl-service
    - numpy
  imports:
    - mkl_random
    - mkl_random.mklrand

about:
  home: https://github.com/IntelPython/mkl_random
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  description: NumPy-based implementation of random number generation sampling using Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices of sampling algorithms available in MKL.
  summary: Intel (R) MKL-powered package for sampling from common probability distributions into NumPy arrays.
  dev_url: https://github.com/IntelPython/mkl_random
  doc_url: https://github.com/IntelPython/mkl_random

extra:
  recipe-maintainers:
    - oleksandr-pavlyk
