travis:
  secure:
    BINSTAR_TOKEN: aqMPbvLsmYgd/9xqfYxs93jLo+BPK3L77KdGO0UsAv0ePGb1KujNwnW5IfIpyrx+gV8HhPIGuLacT8bg/8Cuqjm0Wz5CyRjy7bKE1KMiFHBTJpO1bBm+J5q6eczIlL8lnJbNxa8l/wPMsDrJqJXefcnqWwwGdJW5qMzPBNHXF9nhjovnEhbdRip/R1HsqkcRNvwvD8jwjsLAs2/j7DaEKBKwP4vcCriRcWV5pLFznU0H+wKb8O741dhKZ6aggzsSvo9F8OdMyZFsO2W7CQFRzzwugPl9yL2C44XBEU4CirGwRtEM16w0grPAUO7QvePnKQWtyGhv4y94vEk0LjjJQpPYovHRth9sDAbCl2VZ6/Vp/E5NqJutXKM1yWDYws6MpLyQFl2PzrP5/4xuet9FTTVCwO0ouVvI4/DtvoMH40zt5uTq41ovgr3OMMNfyotrcCkIc7nvxYpGodK+YJr/V3vRrFOUjbQ4rxuTE/oU8IwEmGqL0xklj6v8m56B1LsqbbLdIQ0MzwdGFvAVOEjY0fF7Y755O/IOciVBiWdKWX77gS4I5aVBHEkRi+N92xfjEnx5P1Q6nzapZeTCrvZA9bR/5z6CARdWssmKzBPZyl2k7WF3hvPDyWPMoYsz9pUcA4CvUEpztnzghg5Jb0rxdH0m62yEJgc3bab/8sCiTUY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
